export const AUTH_PENDING = "AUTH_PENDING";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_SUCCESS = "AUTH_SUCCESS";

export const SERVERS_FETCH_SUCCESS = "SERVERS_FETCH_SUCCESS";
export const SERVERS_FETCH_ERROR = "SERVERS_FETCH_ERROR";
export const SERVERS_FETCH_PENDING = "SERVERS_FETCH_PENDING";
export const SERVERS_RESET = "SERVERS_RESET";
